// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e4ddeda801819f05f9faef22a81056622b2bf347/pg-promise/pg-promise.d.ts
// Type definitions for pg-promise
// Project: https://github.com/vitaly-t/pg-promise
// Definitions by: vvakame <https://github.com/vvakame>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// deprecated. see https://github.com/vitaly-t/pg-promise/tree/master/typescript
// NOTE https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8956