/* TEST */
var key;
var test = {
  "xtirqfpmqwnjxqj": false,
  "lalitta's": true,
  "thousandths": true,
  "forepanner's": false,
  "lunarians": true,
  "balleyoptunly": false,
  "daumier's": true,
  "xtyoshkiuxkc": false,
  "kles": false,
  "bellackely": false,
  "rgutiscisut": false,
  "exchanger": true,
  "lrcmcfyhuogjhsxksj": false,
  "semilatus": true,
  "zionists": true,
  "sugardholle's": false,
  "scoffers": true,
  "freebaser's": true,
  "glogallnecal": false,
  "jaddictor": false,
  "phallize": false,
  "ignougz'mozdves'": false,
  "larobreropintinhintrremat": false,
  "wivitristimeshielelig": false,
  "ycxmr'jio'uyxgwqv": false,
  "vat": true,
  "pelologies": true,
  "defclacdnd": false,
  "barrellaria's": false,
  "oxbird": true,
  "polymath's": true,
  "aizppefcwz": false,
  "xjhtng": false,
  "danapshook": false,
  "hehmtwuxkxdlsmaubmus": false,
  "renotation": true,
  "chiefship's": true,
  "macrobiotics's": true,
  "transplanchedly": false,
  "nonarithmetical": true,
  "bjifen": false,
  "haliogravurais": false,
  "sanwovliecatasovidas": false,
  "angara's": true,
  "corsleted": true,
  "mehbugqnwcjbio": false,
  "choromarere's": false,
  "dooflourkey": false,
  "fiktuncesmtjk": false,
  "lifefulness": true,
  "avianizations": false,
  "l'jktzxnsk": false,
  "thessalian": true,
  "fricandoes": true,
  "saningful": false,
  "billings's": true,
  "fadz": false,
  "literalistian": false,
  "parabranchial": true,
  "fumsisks": false,
  "massessionist": false,
  "toetcdtuazvdhngijcwveapile": false,
  "aler's": false,
  "ceiric": false,
  "hostage": true,
  "bahawalpurgisnacht": false,
  "repers": false,
  "scurephan": false,
  "unmeasurably": true,
  "blacks": true,
  "hallopeanly": false,
  "ancer's": false,
  "versets": true,
  "lecotropal": true,
  "idcozbsmoss": false,
  "quacksalver's": true,
  "nonvitative": false,
  "unspuriously": true,
  "subdelegation": true,
  "hichens": true,
  "kfhvt": false,
  "tenline": true,
  "thunnus": true,
  "dakksj": false,
  "superzealously": true,
  "larrikinalian": true,
  "conse": false,
  "biedermann": true,
  "gurish": true,
  "destinate": true,
  "foretsophs": false,
  "kunigsberg's": true,
  "hea": false,
  "rictisesmattengy": false,
  "hyperoxygenise": true,
  "scaphologists": false,
  "bombyliidae": true,
  "hangdog's": true,
  "lagos's": true,
  "conda": true
};
var error = 0;
for (key in test) {
  if (check(key) !== test[key]) {
    console.log('Distinction in: ' + '"' + key + '"');
    error++;
  }
}
console.log('Total distinction = ' + error);
/* END TEST */